version: '3'

services:
  server:
    build: .
    ports:
      - "50051:50051"
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "7860:7860"
    environment:
      - GRPC_SERVER=server:50051
    depends_on:
      - server
    restart: unless-stopped