# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import story_audio_pb2 as story__audio__pb2


class StoryAudioServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateAudio = channel.unary_unary(
                '/story_audio.StoryAudioService/GenerateAudio',
                request_serializer=story__audio__pb2.StoryRequest.SerializeToString,
                response_deserializer=story__audio__pb2.AudioResponse.FromString,
                )


class StoryAudioServiceServicer(object):
    """Service definition
    """

    def GenerateAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoryAudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAudio,
                    request_deserializer=story__audio__pb2.StoryRequest.FromString,
                    response_serializer=story__audio__pb2.AudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'story_audio.StoryAudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StoryAudioService(object):
    """Service definition
    """

    @staticmethod
    def GenerateAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/story_audio.StoryAudioService/GenerateAudio',
            story__audio__pb2.StoryRequest.SerializeToString,
            story__audio__pb2.AudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
